options:
  logging: CLOUD_LOGGING_ONLY  # Or use `gs://learn-rust-bucket` for a storage bucket
  logging_bucket: "gs://learn-rust-bucket"

steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/my-rust-app", "."]
  
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/my-rust-app"]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "my-rust-app"
      - "--image=gcr.io/$PROJECT_ID/my-rust-app"
      - "--region=us-central1"
      - "--platform=managed"
      - "--allow-unauthenticated"
      - "--set-env-vars=PORT=8080"

images:
  - "gcr.io/$PROJECT_ID/my-rust-app"
