options:
  logging: CLOUD_LOGGING_ONLY  # Logs go to Cloud Logging
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET  # Uses a regional user-owned bucket

steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/my-rust-app", "."]
  
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/my-rust-app"]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "my-rust-app"
      - "--image=gcr.io/$PROJECT_ID/my-rust-app"
      - "--region=us-central1"
      - "--platform=managed"
      - "--allow-unauthenticated"

images:
  - "gcr.io/$PROJECT_ID/my-rust-app"
